# Generated by Django 3.2.6 on 2021-08-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Contact',
        ),
    ]
